steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - '-b'
      - '${BRANCH_NAME}'
      - '--single-branch'
      - >-
        https://${_GIT_USER_}:${_GIT_TOKEN_}@github.com/${_GIT_ORG_}/${REPO_NAME}.git
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        asia-south1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${REPO_NAME}:${BRANCH_NAME}
      - '--file=Dockerfile'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-south1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${REPO_NAME}:${BRANCH_NAME}
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - ssh
      - $_SERVER
      - '--zone'
      - $_ZONE
      - '--command'
      - '${_DIR_} && ${_COMMAND_}'
      - '--quiet'
timeout: 1000s
